// Code generated by protoc-gen-days (generator/spanner) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package spanner

import (
	"context"

	"cloud.google.com/go/spanner"

	"github.com/karamaru-alpha/days/pkg/derrors"
	"github.com/karamaru-alpha/days/pkg/domain/entity/transaction"
	"github.com/karamaru-alpha/days/pkg/infra/spanner/repository/base"
)

func bufferWrite(ctx context.Context, spannerRWTx *spanner.ReadWriteTransaction) error {
	mutations := make([]*spanner.Mutation, 0)
	for _, operation := range base.ExtractUserMutationWaitBuffer(ctx).GetState() {
		columns, values := operation.GetColumnsAndValuesWithPK()
		switch operation.Type {
		case base.OperationTypeInsert:
			mutations = append(mutations, spanner.Insert(transaction.UserTableName, columns, values))
		case base.OperationTypeUpdate:
			mutations = append(mutations, spanner.Update(transaction.UserTableName, columns, values))
		case base.OperationTypeDelete:
			mutations = append(mutations, spanner.Delete(transaction.UserTableName, spanner.Key(values)))
		}
	}
	for _, operation := range base.ExtractUserExampleMutationWaitBuffer(ctx).GetState() {
		columns, values := operation.GetColumnsAndValuesWithPK()
		switch operation.Type {
		case base.OperationTypeInsert:
			mutations = append(mutations, spanner.Insert(transaction.UserExampleTableName, columns, values))
		case base.OperationTypeUpdate:
			mutations = append(mutations, spanner.Update(transaction.UserExampleTableName, columns, values))
		case base.OperationTypeDelete:
			mutations = append(mutations, spanner.Delete(transaction.UserExampleTableName, spanner.Key(values)))
		}
	}
	if err := spannerRWTx.BufferWrite(mutations); err != nil {
		return derrors.Wrap(err, derrors.Internal, "fail to buffer write to spanner")
	}

	return nil
}
