// Code generated by protoc-gen-days (generator/enum) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package enum

type ErrorCodeSlice []ErrorCode

var ErrorCodeValues = ErrorCodeSlice{
	ErrorCode_INVALID_ARGUMENT,
	ErrorCode_INTERNAL,
}

func (e ErrorCode) EncodeSpanner() (any, error) {
	return int64(e), nil
}

func (e ErrorCodeSlice) EncodeSpanner() (any, error) {
	slice := make([]int64, 0, len(e))
	for _, v := range e {
		slice = append(slice, int64(v))
	}
	return slice, nil
}
