// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: enums/error_code.proto

package enum

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// error code
type ErrorCode int32

const (
	ErrorCode_UNKNOWN ErrorCode = 0
	// InvalidArgument
	ErrorCode_INVALID_ARGUMENT ErrorCode = 1
	// InternalServerError
	ErrorCode_INTERNAL ErrorCode = 2
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_ARGUMENT",
		2: "INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":          0,
		"INVALID_ARGUMENT": 1,
		"INTERNAL":         2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_enums_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_enums_error_code_proto_rawDescGZIP(), []int{0}
}

var File_enums_error_code_proto protoreflect.FileDescriptor

var file_enums_error_code_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x3c, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e,
	0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x02, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x72, 0x61, 0x6d, 0x61, 0x72, 0x75, 0x2d,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x64, 0x61, 0x79, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_enums_error_code_proto_rawDescOnce sync.Once
	file_enums_error_code_proto_rawDescData = file_enums_error_code_proto_rawDesc
)

func file_enums_error_code_proto_rawDescGZIP() []byte {
	file_enums_error_code_proto_rawDescOnce.Do(func() {
		file_enums_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_enums_error_code_proto_rawDescData)
	})
	return file_enums_error_code_proto_rawDescData
}

var file_enums_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_error_code_proto_goTypes = []interface{}{
	(ErrorCode)(0), // 0: enums.error_code.ErrorCode
}
var file_enums_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_error_code_proto_init() }
func file_enums_error_code_proto_init() {
	if File_enums_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enums_error_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_error_code_proto_goTypes,
		DependencyIndexes: file_enums_error_code_proto_depIdxs,
		EnumInfos:         file_enums_error_code_proto_enumTypes,
	}.Build()
	File_enums_error_code_proto = out.File
	file_enums_error_code_proto_rawDesc = nil
	file_enums_error_code_proto_goTypes = nil
	file_enums_error_code_proto_depIdxs = nil
}
