// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: options/entity/entity.proto

package entity

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema *FieldOption_Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *FieldOption) Reset() {
	*x = FieldOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_entity_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption) ProtoMessage() {}

func (x *FieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_options_entity_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption.ProtoReflect.Descriptor instead.
func (*FieldOption) Descriptor() ([]byte, []int) {
	return file_options_entity_entity_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOption) GetSchema() *FieldOption_Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type FieldOption_Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk bool `protobuf:"varint,1,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (x *FieldOption_Schema) Reset() {
	*x = FieldOption_Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_entity_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption_Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption_Schema) ProtoMessage() {}

func (x *FieldOption_Schema) ProtoReflect() protoreflect.Message {
	mi := &file_options_entity_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption_Schema.ProtoReflect.Descriptor instead.
func (*FieldOption_Schema) Descriptor() ([]byte, []int) {
	return file_options_entity_entity_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FieldOption_Schema) GetPk() bool {
	if x != nil {
		return x.Pk
	}
	return false
}

var file_options_entity_entity_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOption)(nil),
		Field:         50010,
		Name:          "options.entity.field",
		Tag:           "bytes,50010,opt,name=field",
		Filename:      "options/entity/entity.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional options.entity.FieldOption field = 50010;
	E_Field = &file_options_entity_entity_proto_extTypes[0]
)

var File_options_entity_entity_proto protoreflect.FileDescriptor

var file_options_entity_entity_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x63, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a,
	0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x18, 0x0a, 0x06, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x70, 0x6b, 0x3a, 0x52, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xda, 0x86, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x72, 0x61, 0x6d, 0x61, 0x72, 0x75, 0x2d,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x64, 0x61, 0x79, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x62, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_options_entity_entity_proto_rawDescOnce sync.Once
	file_options_entity_entity_proto_rawDescData = file_options_entity_entity_proto_rawDesc
)

func file_options_entity_entity_proto_rawDescGZIP() []byte {
	file_options_entity_entity_proto_rawDescOnce.Do(func() {
		file_options_entity_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_options_entity_entity_proto_rawDescData)
	})
	return file_options_entity_entity_proto_rawDescData
}

var file_options_entity_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_options_entity_entity_proto_goTypes = []interface{}{
	(*FieldOption)(nil),               // 0: options.entity.FieldOption
	(*FieldOption_Schema)(nil),        // 1: options.entity.FieldOption.Schema
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_options_entity_entity_proto_depIdxs = []int32{
	1, // 0: options.entity.FieldOption.schema:type_name -> options.entity.FieldOption.Schema
	2, // 1: options.entity.field:extendee -> google.protobuf.FieldOptions
	0, // 2: options.entity.field:type_name -> options.entity.FieldOption
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_options_entity_entity_proto_init() }
func file_options_entity_entity_proto_init() {
	if File_options_entity_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_options_entity_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_options_entity_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption_Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_options_entity_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_options_entity_entity_proto_goTypes,
		DependencyIndexes: file_options_entity_entity_proto_depIdxs,
		MessageInfos:      file_options_entity_entity_proto_msgTypes,
		ExtensionInfos:    file_options_entity_entity_proto_extTypes,
	}.Build()
	File_options_entity_entity_proto = out.File
	file_options_entity_entity_proto_rawDesc = nil
	file_options_entity_entity_proto_goTypes = nil
	file_options_entity_entity_proto_depIdxs = nil
}
