// Code generated by protoc-gen-days (generator/spanner) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package transaction

import (
	"context"

	"github.com/karamaru-alpha/days/pkg/domain/database"
	"github.com/karamaru-alpha/days/pkg/domain/entity/transaction"
)

type UserExampleRepository interface {
	LoadByPK(ctx context.Context, tx database.ROTx, pk *transaction.UserExamplePK) (*transaction.UserExample, error)
	LoadByPKs(ctx context.Context, tx database.ROTx, pks transaction.UserExamplePKs) (transaction.UserExampleSlice, error)
	SelectByPK(ctx context.Context, tx database.ROTx, pk *transaction.UserExamplePK) (*transaction.UserExample, error)
	SelectByPKs(ctx context.Context, tx database.ROTx, pks transaction.UserExamplePKs) (transaction.UserExampleSlice, error)
	SelectAll(ctx context.Context, tx database.ROTx, limit int, offset int) (transaction.UserExampleSlice, error)
	SelectByUserID(ctx context.Context, tx database.ROTx, UserID string) (transaction.UserExampleSlice, error)
	SelectByUserIDs(ctx context.Context, tx database.ROTx, UserIDs []string) (transaction.UserExampleSlice, error)
	SelectByIdxExampleWithExample(ctx context.Context, tx database.ROTx, Example int64) (transaction.UserExampleIdxExampleSlice, error)
	SelectByIdxExampleWithExamples(ctx context.Context, tx database.ROTx, Examples []int64) (transaction.UserExampleIdxExampleSlice, error)
	Insert(ctx context.Context, tx database.RWTx, row *transaction.UserExample) error
	BulkInsert(ctx context.Context, tx database.RWTx, rows transaction.UserExampleSlice) error
	Update(ctx context.Context, tx database.RWTx, row *transaction.UserExample) error
	Save(ctx context.Context, tx database.RWTx, row *transaction.UserExample) error
	Delete(ctx context.Context, tx database.RWTx, pk *transaction.UserExamplePK) error
	BulkDelete(ctx context.Context, tx database.RWTx, pks transaction.UserExamplePKs) error
}
