package core

import (
	"fmt"
	"text/template"

	"github.com/Masterminds/sprig/v3"
)

const baseTemplateStringFormat = `
{{ define "autogen_comment" -}}
// Code generated by protoc-gen-days (%s) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
{{ end }}
`

func GetBaseTemplate(name string) *template.Template {
	return template.Must(template.New(name).Funcs(sprig.TxtFuncMap()).Parse(fmt.Sprintf(baseTemplateStringFormat, name)))
}
