// Code generated by protoc-gen-days (generator/spanner) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package base

const (
	UserExampleTableName             = "UserExample"
	UserExampleColumnNameUserID      = "UserID"
	UserExampleColumnNameExample     = "Example"
	UserExampleColumnNameCreatedTime = "CreatedTime"
	UserExampleColumnNameUpdatedTime = "UpdatedTime"
)

var (
	UserExampleColumnNames = []string{
		UserExampleColumnNameUserID,
		UserExampleColumnNameExample,
		UserExampleColumnNameCreatedTime,
		UserExampleColumnNameUpdatedTime,
	}
)
