// Code generated by protoc-gen-days (generator/spanner) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package base

const (
	UserTableName             = "User"
	UserColumnNameUserID      = "UserID"
	UserColumnNameName        = "Name"
	UserColumnNameCreatedTime = "CreatedTime"
	UserColumnNameUpdatedTime = "UpdatedTime"
)

var (
	UserColumnNames = []string{
		UserColumnNameUserID,
		UserColumnNameName,
		UserColumnNameCreatedTime,
		UserColumnNameUpdatedTime,
	}
)
