// Code generated by protoc-gen-days (generator/rpc) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package di

import (
	"net/http"

	"connectrpc.com/connect"
	"go.uber.org/fx"

	"github.com/karamaru-alpha/days/pkg/cmd/api/handler/user"
	"github.com/karamaru-alpha/days/pkg/pb/rpc/api/apiconnect"
)

var handlerSet = fx.Provide(
	user.NewHandler,
)

func invokeHandler(
	mux *http.ServeMux,
	opts []connect.HandlerOption,
	userHandler apiconnect.UserHandler,
) {
	mux.Handle(apiconnect.NewUserHandler(userHandler, opts...))
}
