// Code generated by protoc-gen-days (generator/rpc) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package apiconnect

import (
	"connectrpc.com/connect"

	"github.com/karamaru-alpha/days/pkg/domain/dto"
)

var Specs = dto.ConnectSpecs{
	{Procedure: UserUpdateNameProcedure, Description: "", IdempotencyLevel: connect.IdempotencyUnknown},
}
