// Code generated by protoc-gen-days (generator/entity) . DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package transaction

// User
type User struct {
	// UserID
	UserID string `json:"userID,omitempty"`
	// Name
	Name string `json:"name,omitempty"`
}

type UserSlice []*User

type UserMapByPK map[string]*User

func (s UserSlice) CreateMapByPK() UserMapByPK {
	m := make(UserMapByPK, len(s))
	for _, row := range s {
		m[row.UserID] = row
	}
	return m
}

type UserPK struct {
	UserID string
}

type UserPKs []*UserPK

func (e *UserPK) ToEntity() *User {
	return &User{
		UserID: e.UserID,
	}
}
